### PR TITLE
Swap increase and decrease buttons

### PR DESCRIPTION
**Pull request by goncy**
Move decrease button to the left:

image

### CODE REVIEW

**Review by nickserv — APPROVED** [review]

**Comment by goncy** [comment]
@nickmccurdy want me to close this?

**Comment by nickserv** [comment]
I'm fine with it, but I want to see if @markerikson or @BenLorantfy have any opinions first

**Comment by BenLorantfy** [comment]
Seems good, most counter UIs seem to have the decrease button on the left: https://www.google.com/search?q=counter+ui&tbm=isch&sclient=img

**Comment by nickserv** [comment]
Seems ready to merge

**Pull request merged**
