### PR TITLE
Update template for React 18 and React-Redux v8

### PR DESCRIPTION
**Pull request by souzaramon**
#52

### CODE REVIEW

**Comment by souzaramon** [comment]
I think that's it

**Comment by markerikson** [comment]
Hmm. Looks like our Github workflow needs to be updated to set `NODE_ENV=test` ?

```
Run npm run lint

> cra-template-redux@1.0.3 lint /home/runner/work/cra-template-redux/cra-template-redux
> eslint './template/src/**/*.js'

/home/runner/work/cra-template-redux/cra-template-redux/template/src/App.js
  0:0  error  Parsing error: [BABEL] /home/runner/work/cra-template-redux/cra-template-redux/template/src/App.js: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined. (While processing: "/home/runner/work/cra-template-redux/cra-template-redux/node_modules/babel-preset-react-app/index.js")
  ```

Can I have you tweak that and get the check passing?

**Comment by souzaramon** [comment]
> Hmm. Looks like our Github workflow needs to be updated to set `NODE_ENV=test` ?
> 
> ```
> Run npm run lint
> 
> > cra-template-redux@1.0.3 lint /home/runner/work/cra-template-redux/cra-template-redux
> > eslint './template/src/**/*.js'
> 
> /home/runner/work/cra-template-redux/cra-template-redux/template/src/App.js
>   0:0  error  Parsing error: [BABEL] /home/runner/work/cra-template-redux/cra-template-redux/template/src/App.js: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined. (While processing: "/home/runner/work/cra-template-redux/cra-template-redux/node_modules/babel-preset-react-app/index.js")
> ```
> 
> Can I have you tweak that and get the check passing?

Sure, I'm sorry for not seeing this 🤦🏻

**Comment by souzaramon** [comment]
Here this problem has gotten more atencion:

https://github.com/facebook/create-react-app/issues/2377

Not sure if its the best solution, but the minimal change its just set NODE_ENV, so I add the cross-env lib. I'll make some tests to see if everything is working fine, but I'll appreciate any comment in this

**Comment by souzaramon** [comment]
> Hmm. Looks like our Github workflow needs to be updated to set `NODE_ENV=test` ?
> 
> ```
> Run npm run lint
> 
> > cra-template-redux@1.0.3 lint /home/runner/work/cra-template-redux/cra-template-redux
> > eslint './template/src/**/*.js'
> 
> /home/runner/work/cra-template-redux/cra-template-redux/template/src/App.js
>   0:0  error  Parsing error: [BABEL] /home/runner/work/cra-template-redux/cra-template-redux/template/src/App.js: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined. (While processing: "/home/runner/work/cra-template-redux/cra-template-redux/node_modules/babel-preset-react-app/index.js")
> ```
> 
> Can I have you tweak that and get the check passing?

I add NODE_ENV=test in the github flow and in dev I had to add NODE_ENV=dev too, that is a issue about this here.

https://github.com/facebook/create-react-app/issues/2377

And thinking about windows env, cross-env should be the simplier solution.

**Comment by markerikson** [comment]
Looks good!

**Pull request merged**
